Create main.yml
wilmhit/easyWarehouse pull request #13
Opened 2021-04-14 21:04 UTC by wilmhit

2021-04-15 06:18 UTC, songofroland requested changes

2021-04-15 06:18 UTC, songofroland commented on .github/workflows/main.yml
> +      - uses: piotrpawlaczek/python-blacken@release/stable
let's rather use `python-slim` image and run:
```
poetry install
cd easywarehouse
poetry run black . --check
poetry run isort . --check
```

2021-04-21 10:36 UTC, wilmhit commented on .github/workflows/main.yml
> +      - uses: piotrpawlaczek/python-blacken@release/stable
there is no such thing as `python-slim`

2021-04-21 13:24 UTC, songofroland approved these changes

2021-04-21 18:23 UTC, merged