Html
wilmhit/easyWarehouse pull request #15
Opened 2021-04-28 15:15 UTC by wrobelmichal

2021-04-28 20:19 UTC, wilmhit requested changes
You will need to:
 - Test this in a browser. In order to do that You need to modify python view functions to render templates (look inside `views.py`).
 - Add some content to index.html.
 - Make login.html use base template.
 - Merge in changes from main branch.

2021-04-28 20:19 UTC, wilmhit commented on easywarehouse/templates/base.html
> +            Copyright 2021
I dont think every page is going to need a footer. Maybe it should be in index.html?

2021-04-28 20:19 UTC, wilmhit commented on easywarehouse/templates/base.html
> +            {% block title %}
Something like `{{ title }}` should be enough here. Title will always be a single string, so there is no need to use `block` here

2021-04-28 20:19 UTC, wilmhit commented on easywarehouse/templates/base.html
> +
Are you sure you will need that many `{% block %}` tags?

2021-04-28 20:19 UTC, wilmhit commented on easywarehouse/templates/index.html
> +
Where is content in all those blocks?
It is index page so make a searchbox and write some text for the user

2021-04-29 16:27 UTC, wrobelmichal reviewed
Changes done.

2021-04-29 17:03 UTC, songofroland requested changes

2021-04-29 17:03 UTC, songofroland commented on easywarehouse/templates/index.html
> +<form>
Search should not be placed in the header, rather use `content`

2021-04-29 17:03 UTC, songofroland commented on easywarehouse/templates/base.html
> +        <header>
+1 for using semantic tags

2021-04-29 17:03 UTC, songofroland commented on easywarehouse/templates/base.html
> +        {% block footer %}
Please close it in `<footer>` tags as header above

2021-04-29 17:10 UTC, wilmhit requested changes

2021-04-29 17:10 UTC, wilmhit commented on easywarehouse/products/views.py
> +    return render(request, "../templates/index.html", content_type="text/html")
Please always read official documentation. [render](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#render). Here:
 - `content_type` is useless since `text/html` is default value
 - You have not provided context, so `{{ title  }}` is empty.
 - Django looks for templates in template folder, so `../templates` tells it to leave this folder and go back inside.

2021-04-29 17:10 UTC, wilmhit commented on easywarehouse/templates/base.html
> +            {{ title }}
Maybe wrap this in `{% if %}` to check if title exists and provide default value?

2021-04-29 17:10 UTC, wilmhit commented on easywarehouse/templates/base.html
> +            {{ title }}
[Here](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#if) is an example.

2021-04-29 18:48 UTC, wilmhit approved these changes

2021-04-30 12:25 UTC, songofroland approved these changes

2021-04-30 14:03 UTC, merged