Added draft of image upload
wilmhit/easyWarehouse pull request #25
Opened 2021-05-09 20:55 UTC by wilmhit

2021-05-13 17:49 UTC, songofroland requested changes
:+1:

2021-05-13 17:49 UTC, songofroland commented on easywarehouse/easywarehouse/settings.py
> +AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
If you're keen to learn cloud & devops it would be nice to create an AWS organization and add us, otherwise you'll need to generate the creds manually and send us.

2021-05-13 17:49 UTC, songofroland commented on easywarehouse/easywarehouse/storage_backends.py
> +    default_acl = 'public-read'
so let's use the one from config :wink:

2021-05-13 17:49 UTC, songofroland commented on easywarehouse/products/forms.py
> +        fields = ["image"]
eof (here and in htmls)

2021-05-13 17:49 UTC, songofroland commented on pyproject.toml
> +boto3 = "1.17.58"
don't we need to add the Pillow?
https://docs.djangoproject.com/en/3.2/ref/models/fields/#imagefield
_Requires the Pillow library._

2021-05-13 17:49 UTC, songofroland commented on easywarehouse/products/views.py
> +class ImageDetails(LoginRequiredMixinm, DetailView):
Let's create app `media` or `images`. One app per one model is nice convention in django.

2021-05-13 17:49 UTC, songofroland commented on easywarehouse/products/models.py
> +from easywarehouse.storage_backends import S3
I'd either move this class somewhere to the new app `media` or name this module in more general way e.g. `aws`

2021-05-14 15:56 UTC, wilmhit commented
Nice review, but code is still WIP. Either way I was gonna ask what to do with creds so now thats solved.

2021-05-17 18:29 UTC, songofroland commented on .gitignore
> +s3.env
what's that?

2021-05-17 18:29 UTC, songofroland commented on easywarehouse/easywarehouse/settings.py
> +if os.getenv("USE_AWS_S3") == "TRUE":
why not use by default?

2021-05-17 18:29 UTC, songofroland commented on easywarehouse/templates/images/list.html
> +<!-- <a href=" url 'images-add' ">Add new image</a> -->
Why?

2021-05-18 11:08 UTC, wilmhit commented on easywarehouse/templates/images/list.html
> +<!-- <a href=" url 'images-add' ">Add new image</a> -->
because i forgot to uncomment this

2021-05-18 11:09 UTC, wilmhit commented on .gitignore
> +s3.env
Thats my s3 credentials. Ill share it on sercure channel

2021-05-18 11:18 UTC, songofroland commented on .gitignore
> +s3.env
It's common to store them in `~/.aws/credentials`

2021-05-18 15:06 UTC, songofroland commented on easywarehouse/easywarehouse/settings.py
> +AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
Are those used anywhere btw? 😉

2021-05-18 15:07 UTC, songofroland commented on easywarehouse/easywarehouse/settings.py
> +AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
boto consumes them by default so it's not needed to specify them in settings, sorry but I forgot that

2021-05-18 17:37 UTC, wilmhit commented on easywarehouse/easywarehouse/settings.py
> +AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
[Source](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables)

2021-05-18 17:46 UTC, wilmhit commented
WIP

2021-05-18 17:52 UTC, songofroland approved these changes

2021-05-18 17:54 UTC, merged