Implement searching products
wilmhit/easyWarehouse pull request #35
Opened 2021-05-26 18:07 UTC by songofroland

resolves #20 
resolves #21

2021-05-28 16:07 UTC, wilmhit requested changes

2021-05-28 16:07 UTC, wilmhit commented on easywarehouse/templates/products/list.html
> -  </ul>
What is your HTML formatter?

2021-05-28 16:07 UTC, wilmhit commented on easywarehouse/products/models.py
> +    main_image_url = models.URLField(null=True, blank=True)
And there is no migration for this change

2021-05-28 17:13 UTC, songofroland commented on easywarehouse/products/migrations/0006_auto_20210525_0739.py
> -        ('products', '0005_auto_20210521_1325'),
should be, I'll have a look

2021-05-28 17:13 UTC, songofroland commented on easywarehouse/products/models.py
> +    main_image_url = models.URLField(null=True, blank=True)
> And there is no migration for this change

Good catch, I'll add it

> This should be a relation to an image. Image class stores urls.
Actually none of the classes stores URL now, They are resolved dynamically. 

I found out that the easiest way is to manually enter the URL per each product. Also, this is somehow a config value - it tells that the particulat image is the main image of the product. If this does not convince you, let's make a call

2021-05-28 17:13 UTC, songofroland commented on easywarehouse/templates/products/list.html
> -  </ul>
Pycharm's default, we can agree on one style though

2021-05-28 17:13 UTC, songofroland commented on logstash/logstash.conf
> +        # TODO: Join products with categories
Yeah, I'm not keen to invest more time this week. I'm pretty sure there will be some testing made, and we'll check that searching on categories does not work, so I'd park it for now

2021-05-29 08:19 UTC, wilmhit approved these changes

2021-05-29 08:37 UTC, merged