ElasticSearch pagination
wilmhit/easyWarehouse pull request #59
Opened 2021-06-05 15:53 UTC by songofroland

2021-06-05 20:28 UTC, wilmhit requested changes

2021-06-05 20:28 UTC, wilmhit commented on easywarehouse/products/views.py
> +    paginate_by = 10
This will probably be often changed. Let's do CONSTANT somewhere at the top.

2021-06-05 20:28 UTC, wilmhit commented on easywarehouse/products/views.py
> +    paginate_by = 30
Same here

2021-06-05 20:28 UTC, wilmhit commented on easywarehouse/templates/base.html
> +            <div class="pagination-buttons">
This shouldn't be in base template. Only few <strike>pages</strike> urls will have pages.

2021-06-05 20:28 UTC, wilmhit commented on easywarehouse/products/documents.py
> +    def __init__(self, search_object):
type hint for `search_object` would make code a little clearer (if the type is verbose).

2021-06-06 14:39 UTC, songofroland commented on easywarehouse/products/views.py
> +    paginate_by = 10
It rather won't be changed that often, also this class looks like a config on its own so imho it is a little bit overengineering to add an additional variable

2021-06-06 14:53 UTC, songofroland commented on easywarehouse/templates/employee/base_list.html
> +    <div class="pagination-buttons">
It is duplicated but it would require extra work to avoid this, and yet it may need to be displayed in a different fashion for the staff in future

2021-06-08 12:30 UTC, wilmhit approved these changes

2021-06-08 12:53 UTC, merged